### ISSUE TITLE
Horizontal scrollbar appears when I click the "Settings" menu

### ISSUE THREAD

**Issue by vaulttech** [explosion/displacy#13]
This is a simple thing, but I was wondering if I am the only one who has this "issue".

When I click in the "Model" menu, I get the two options, accompanied by a vertical scroll bar to the right. I take that vertical scroll bar as ok (though unnecessary). But when I click in the "Settings" menu, I see the options along with two scroll bars: one vertical and one horizontal. I find this very strange. I believe there must be some very simple size miscalculation somewhere (but I am noob with all these web stuff and still didn't manage to figure out exactly where).

I see this happening in both Chrome 58.0.3029.81 (64-bit) and Firefox 52.0 (32-Bit), in Windows 7 Ultimate SP1 64-bit.
![issue_displacy](https://cloud.githubusercontent.com/assets/419907/25526013/f89c1ebc-2c11-11e7-88a5-f72ff7cd6a8b.png)

**Comment by ines** [comment]
Sorry about this – I kinda regret doing the dropdowns in such a hacky way just to save a few lines of code.

I think the main problem is `overflow-y: scroll` [here](https://github.com/explosion/displacy/blob/master/assets/css/_ui.sass#L166), which should be `overflow-y: auto`. (This is easy to miss on Mac, because unlike on Windows, scrollbars are usually hidden by default.) `overflow-x: hidden` should hide the horizontal scrollbar – but it's also kinda hacky, because it doesn't actually fix the sizing problem, it just hides the overflow.

When we update displaCy to use the new spaCy models, I definitely wanna give the front-ends a makeover, fix all of this and make it easier to use and adapt the full demo.

**Comment by vaulttech** [comment]
Ohh... thank you. I would have taken a lot more time trying to figure out where to look at.
