### ISSUE TITLE
Multiple diplaCy instances on the same page?

### ISSUE THREAD

**Issue by riedelcastro** [explosion/displacy#5]
First of all, thanks for displaCy, it's great!

I am using several displaCy instances on the same page (a jupyter notebook, in fact). I have noticed that this seems to sometimes confuse the rendering. In particular, the arc labels seem get misplaced. I attached a screenshot of this behaviour. 

I am wondering: are multiple instances supported, and I may be using them wrongly? I have noticed that the SVG element gets a "id" which suggests there should only be one such graph per page? 

<img width="1013" alt="screenshot 2016-10-29 18 39 38" src="https://cloud.githubusercontent.com/assets/167116/19831649/3c913664-9e07-11e6-9bb6-14f3ddaaaad7.png">

**Comment by ines** [comment]
Ah, so cool to see someone using displaCy with Jupyter Notebook! We've been thinking about writing a plugin for it for a while now, but haven't gotten around to it yet. Was it easy to make it work with displacy.js?

To answer your question: Yes, the problem could definitely the IDs, because they're used to attach the labels to the arcs or rather, align them along the curve.

As a quick fix, you could do the following (untested, but should work): If you're using the `parse()` or `render()` methods, pass in a setting with a unique identifier.
```javsscript
displacy.parse('This is a sentence', 'en', { uiniqueId: '12345' })
```

It'll be available as `settings.uniqueId` in `render()` so you could add:
```javascript
this.uniqueId = settings.uniqueId;
```

And then simply add it to the `id` and `xlink` on lines [149](https://github.com/explosion/displacy/blob/master/assets/js/displacy.js#L149) and [167](https://github.com/explosion/displacy/blob/master/assets/js/displacy.js#L167):
```javascript
id: `${this.uniqueId}-arrow-${i}`
// will produce id="12345-arrow-1" etc.
```

I'll definitely think about a nice and more elegant way to implement this in displaCy, though. It could be nice to have an optional `uniqueId` setting (in case you wanna be 100% sure and use your own), and in all other cases, just generate a simple hash that will probably work fine for 99% of the use cases.

**Comment by riedelcastro** [comment]
Thanks, this worked! Btw, Maybe one could use the `container` id to prefix other ids? I had to make sure that this id is unique anyway. 

As for jupyter intergration: this was quite easy, but I don't really know what I am doing so I think there must be better / more robust ways:

https://github.com/uclmr/stat-nlp-book/blob/51cd67a536d2a87f6331622b2ad1a9dde1acc27d/statnlpbook/transition.py#L99-L99

**Comment by ines** [comment]
True, I forgot about the `container`. The only problem is that it technically allows any selector that can be accessed via `document.querySelector()` (to make it possible to use classes instead of IDs). So even stuff like `.class-one.class-two[title^="foo"]` would be a valid (obviously not recommended).

Thanks for sharing the code – looks good! Making displaCy a "proper" Node module has been on my list for a while now, so I think this would help a lot. 

I'm currently imagining something like:
```javascript
displacy.parse(text, model, settings)
   .then(parse => displacy.toSVG(parse))

**Comment by riedelcastro** [comment]
Ah, cool, so I could potentially render the same parse into several containers? 

One problem with the current jupyter setup is that somehow I have to run the cells again when I re-open a notebook, the cached cell output does not seem to keep the parse. I guess that makes sense because the actual generated HTML doesn't contain the parse, only the call to `render`. Not sure how to best fix this. It may be easier for me to just generate the SVG directly.

**Comment by ines** [comment]
Yeah, I guess this makes sense because it's just modifying the DOM via JavaScript. I would like to integrate a method that just returns the SVG markup as a string, similar to the [`downloadSVG()` function](https://github.com/explosion/displacy/blob/master/assets/js/main.js#L112) I'm currently using for the download button in the demo. (Here it just grabs the SVG markup from the DOM and uses `XMLSerializer()` and `serializeToString()`). 

It's technically not a big deal to generate HTML/XML markup instead of creating DOM elements via displacy.js, but since it's an open source tool, I'd have to implement a bunch of client-side sanitizing to prevent cross-site scripting if I'm doing stuff like `word = "<text>" + word + "</text>"`. (For a use case like yours, this totally doesn't matter.. but if someone just clones the displaCy demo, hosts it somewhere and doesn't sanitize properly on the server, all you need is find a way to make the model return a token like `"><script src="evil.js"></script>`...)

That said, I do have an unpublished version of displacy.js somewhere that still generates the SVG markup as a string (because that was my first approach, before I realised the XSS vulnerability issue). So let me see if I can find the file! Not sure if this helps, but at least here you could call `render()` and it just returns the SVG markup as a string.

**Comment by ines** [comment]
@riedelcastro I finally had some time to play around with Jupyter and made a simple extension that takes a JSON-formatted parse and turns it into a scrollable displaCy visualisation: https://github.com/explosion/spacy-dev-resources/tree/master/jupyter-displacy

Right now, it's probably only suited for use in presentations, since you explicitly need to click the button to render the SVG. But I'd like to add more features to it in the future, like the spaCy + the displaCy REST API, so you can generate the JSON straight from spaCy's parse. I'm pretty new to Jupyter, so any feedback is appreciated!
